version: "3"

services:
    mysqldb:
        image: mysql:latest
        env_file: ./.env
        container_name: mysqldb
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
        networks:
             - DS_SQL_SPRING
#         volumes:
#             - database-volume/schema.sql:/docker-entrypoint-initdb.d/0_init.sql
        expose:
            - "33061"
    backend:
        image: canadaacrbogdantailup30442.azurecr.io/backendrepo:latest
        depends_on:
            - mysqldb
            - rabbit
        container_name: backend
        restart: on-failure
        env_file: ./.env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        networks:
            - DS_SQL_SPRING
    rabbit:
        image: rabbitmq:3-management-alpine
        container_name: "rabbitmq"
        ports:
            - $RABBIT_LOCAL_PORT:$RABBIT_DOCKER_PORT
            - $RABBIT_MANAGEMENT_LOCAL_PORT:$RABBIT_MANAGEMENT_DOCKER_PORT
        networks:
            - DS_SQL_SPRING
networks:
    DS_SQL_SPRING:
        driver: bridge

volumes:
  database-volume:
    driver: local
    driver_opts:
      type: cifs
      o: "mfsymlinks,vers=3.0,username=dscanadastorage,password=fSev39FIzR6gMAi6ch81RVEgjLySJ80o/5ZaH6bK2RSxNQ/K+RZaCSNBA1SLBMk6XYW4m08ZtCct+AStoEcZoA==,addr=dscanadastorage.file.core.windows.net"
      device: "//dscanadastorage.file.core.windows.net/database-volume"
